export const FETCH_WEBSOCKET_DATA = 'FETCH_WEBSOCKET_DATA';
export const FETCH_WEBSOCKET_DATA_SUCCESS = 'FETCH_WEBSOCKET_DATA_SUCCESS';
export const FETCH_WEBSOCKET_DATA_FAIL = 'FETCH_WEBSOCKET_DATA_FAIL';
export const FETCH_WEBSOCKET_DATA_UPDATE = 'FETCH_WEBSOCKET_DATA_UPDATE';
