export const WEBSOCK_URL = 'http://localhost:3010/websock/btc';
export const API_URL = 'http://localhost:3000';


export const ALERTACTIONS = {
    SUCCESS : 'ALERT_SUCCESS',
    ERROR : 'ALERT_ERROR',
    CLEAR : 'ALERT_CLEAR'
};

export const USERACTION = {
    REGISER_REQUEST : 'USER_REGISTER_REQUEST',
    REGISTER_SUCCESS : 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE : 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST : 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS : 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE : 'USERS_LOGIN_FAILURE',

    LOGOUT : 'USERS_LOGOUT',

    GETALL_REQUEST : 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS : 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE : 'USERS_GETALL_FAILURE',

    DELETE_REQUEST : 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS : 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE : 'USERS_DELETE_FAILURE'

}

export const STPDPOSTACTION = {
    /* Community action types */
    COMMUNITYFETCH : 'STPDPOST_FETCHING',
    COMMUNITYLATEST : 'STPDPOST_GET_LATEST',
    COMMUNITYALL : 'STPDPOST_GET_ALL',
    COMMUNITYBYHASH : 'STPDPOST_GET_HASH',
    COMMUNITY_FETCH_ERROR : 'STPDPOST_FETCH_ERROR',

    /*User actions types*/
    CREATEPOST : 'STPDPOST_CREATE',
    USERLATEST : 'STPDPOST_GET_USER_LATEST'

};

